// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgczttyXdaXXa3hfto6HKztRsVhSLl1G4',
    appId: '1:392107277511:web:080c32b7e9157a6c0192e2',
    messagingSenderId: '392107277511',
    projectId: 'dacia-vocal',
    authDomain: 'dacia-vocal.firebaseapp.com',
    storageBucket: 'dacia-vocal.firebasestorage.app',
    measurementId: 'G-H426PT77S3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIFnZS1xxoWy1oDW38uN6bPGF56IuuggQ',
    appId: '1:392107277511:android:4d3edb84c507b4ac0192e2',
    messagingSenderId: '392107277511',
    projectId: 'dacia-vocal',
    storageBucket: 'dacia-vocal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQu12CJ_-j65l20GyxhuFfVATm1bc890A',
    appId: '1:392107277511:ios:98509c4cd43991f60192e2',
    messagingSenderId: '392107277511',
    projectId: 'dacia-vocal',
    storageBucket: 'dacia-vocal.firebasestorage.app',
    iosClientId: '392107277511-tmaldcg3jiigckt4hvmr3l7vl1nhr3oc.apps.googleusercontent.com',
    iosBundleId: 'com.example.englishLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQu12CJ_-j65l20GyxhuFfVATm1bc890A',
    appId: '1:392107277511:ios:98509c4cd43991f60192e2',
    messagingSenderId: '392107277511',
    projectId: 'dacia-vocal',
    storageBucket: 'dacia-vocal.firebasestorage.app',
    iosClientId: '392107277511-tmaldcg3jiigckt4hvmr3l7vl1nhr3oc.apps.googleusercontent.com',
    iosBundleId: 'com.example.englishLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgczttyXdaXXa3hfto6HKztRsVhSLl1G4',
    appId: '1:392107277511:web:2776cbc3bd358a770192e2',
    messagingSenderId: '392107277511',
    projectId: 'dacia-vocal',
    authDomain: 'dacia-vocal.firebaseapp.com',
    storageBucket: 'dacia-vocal.firebasestorage.app',
    measurementId: 'G-QMEZ8PGG23',
  );
}
